apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: dzdzrjt3i-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/dzdzrjt3i-java-quarkus-gitops